import { DEFAULT_MAX_CONVERSATION_CHARS } from "./config.ts";
import type { CompleteTextFn, Snapshot, StateEvidenceBundle } from "./types.ts";

export type SummaryPromptOptions = {
	artifactRefs?: string[];
	maxConversationChars?: number;
	maxPromptChars?: number;
	stateEvidence?: StateEvidenceBundle;
};

export const DEFAULT_MAX_SUMMARY_PROMPT_CHARS = 650_000;

function list(lines: string[]): string {
	return lines.length ? lines.map((line) => `- ${line}`).join("\n") : "- None";
}

function fenced(text: string): string {
	return text.trim() ? `\n\`\`\`text\n${text}\n\`\`\`` : " None";
}

function boundedConversation(messages: string[], maxChars: number): string {
	const full = messages.join("\n\n");
	if (full.length <= maxChars) return full;
	if (maxChars <= 0)
		return `[... Slipstream omitted ${full.length.toLocaleString()} characters from the raw conversation span because protected fixed prompt sections consumed the prompt budget. Full raw span is preserved in local artifacts for later tool-assisted recovery. ...]`;
	const headChars = Math.floor(maxChars * 0.2);
	const tailChars = maxChars - headChars;
	const omittedChars = full.length - maxChars;
	return `${full.slice(0, headChars)}\n\n[... Slipstream omitted ${omittedChars.toLocaleString()} characters from the middle of the raw conversation span. Full raw span is preserved in local artifacts for later tool-assisted recovery, but artifact paths are not visible evidence for this model call. Preserve current, continuation-relevant facts explicitly and mark stale or superseded history instead of restating it as current. ...]\n\n${full.slice(-tailChars)}`;
}

export function isDegenerateCandidateSummary(summary: string): boolean {
	const contentLines = summary
		.trim()
		.split(/\r?\n/)
		.map((line) => line.trim())
		.filter((line) => line && !/^#{1,6}\s+/.test(line));
	return contentLines.length === 0;
}

function capsuleList(lines: string[], limit: number): string {
	const selected = lines.slice(0, limit);
	if (selected.length === 0) return "- None";
	const omitted = lines.length - selected.length;
	const rendered = selected.map((line) => `- ${line}`).join("\n");
	return omitted > 0 ? `${rendered}\n- ... ${omitted} more` : rendered;
}

export function buildCurrentStateCapsule(
	snapshot: Snapshot,
	artifactRefs: string[] = [],
): string {
	const manifest = snapshot.manifest;
	return `## Deterministic Current-State Capsule

Generated by Slipstream from structured session evidence before model prose. Treat this capsule as authoritative current-state scaffolding; use the model-written sections below for narrative detail.

- Session: ${snapshot.sessionId}
- CWD: ${snapshot.cwd}
- First kept entry: ${snapshot.firstKeptEntryId ?? "unknown"}
- Tokens before compaction: ${snapshot.tokensBefore ?? "unknown"}

### Latest user/assistant exchange state
${capsuleList(manifest.latestExchangeState, 5)}

### Terminal final-answer evidence
${capsuleList(manifest.terminalFinalAnswerEvidence, 3)}

### Current verification, risks, and blockers
${capsuleList(
	[
		...manifest.latestSignals.map((signal) => `${signal.kind}: ${signal.text}`),
		...manifest.recentVerification,
		...manifest.openLoops.map((loop) => `${loop.priority}: ${loop.summary}`),
	],
	10,
)}

### User decisions and constraints
${capsuleList(
	[...manifest.userDecisions, ...manifest.constraints].map((fact) => fact.text),
	10,
)}

### Changed files
${capsuleList(
	[
		...manifest.filesModified.map((file) => `modified: ${file}`),
		...manifest.filesDeleted.map((file) => `deleted: ${file}`),
	],
	12,
)}

### Stale or superseded context to ignore
${capsuleList(
	manifest.staleSignals.map((signal) => `${signal.text} — ${signal.reason}`),
	8,
)}

### Recovery artifacts
${capsuleList([...manifest.artifactRefs, ...artifactRefs], 12)}`;
}

export function withCurrentStateCapsule(
	summary: string,
	snapshot: Snapshot,
	artifactRefs: string[] = [],
): string {
	if (summary.trimStart().startsWith("## Deterministic Current-State Capsule"))
		return summary;
	return `${buildCurrentStateCapsule(snapshot, artifactRefs)}\n\n---\n\n${summary.trim()}`;
}

function renderStateEvidence(
	evidence: StateEvidenceBundle | undefined,
): string {
	if (!evidence) return "None";
	return `Generated: ${evidence.generatedAt}
CWD: ${evidence.cwd}

Session distilled facts:
Files read:
${list(evidence.session.filesRead)}

Files modified:
${list(evidence.session.filesModified)}

Files deleted:
${list(evidence.session.filesDeleted)}

Unresolved errors:
${list(evidence.session.unresolvedErrors)}

User decisions:
${list(evidence.session.userDecisions)}

Constraints:
${list(evidence.session.constraints)}

Open loops:
${list(evidence.session.openLoops)}

Verification evidence:
${list(evidence.session.recentVerification)}

Latest compacted updates:
${list(evidence.session.latestUpdates)}

Retained-tail updates still visible after compaction; these are high-priority current-state anchors and override older compacted updates when they conflict:
${list(evidence.session.retainedTailUpdates)}

Latest user/assistant exchange state:
${list(evidence.session.latestExchangeState)}

Terminal final-answer evidence:
${list(evidence.session.terminalFinalAnswerEvidence)}

Latest verification and risk signals:
${list(evidence.session.latestSignals)}

Stale or superseded candidates:
${list(evidence.session.staleSignals)}

Critical literals:
${list(evidence.session.criticalLiterals)}

Read-only git evidence for writer grounding. Use it to understand current code state, but do not copy huge diffs verbatim unless needed to preserve an exact change.
Git available: ${evidence.git.available}
Git errors:
${list(evidence.git.errors)}

Git status --short:${fenced(evidence.git.statusShort)}

Git diff --stat:${fenced(evidence.git.diffStat)}

Full git diff artifact paths:
${list(evidence.git.fullDiffArtifactPaths ?? [])}
Full git diff SHA-256: ${evidence.git.fullDiffSha256 ?? "None"}
Full git diff bytes: ${evidence.git.fullDiffBytes ?? "None"}
Full git diff complete: ${evidence.git.fullDiffComplete ?? "unknown"}
Full git diff preserved: ${evidence.git.fullDiffPreserved ?? "unknown"}

Bounded git diff -U20:${fenced(evidence.git.diff)}
${evidence.git.omittedDiffChars ? `\nOmitted git diff characters: ${evidence.git.omittedDiffChars}` : ""}`;
}

function renderHandoffSignals(
	snapshot: Snapshot,
	artifactRefs: string[],
): string {
	const manifest = snapshot.manifest;
	return `Current handoff signals:
- Trajectory spine inputs: retained-tail updates + latest compacted updates + verification + open loops + stale signals should determine why the next action follows from the latest state.
- Previous summary is a checkpoint to revise, not final truth: ${manifest.previousSummary ? "present" : "none"}
- Latest user/assistant exchange state: ${manifest.latestExchangeState.slice(-4).join(" | ") || "None"}
- Terminal final-answer evidence: ${manifest.terminalFinalAnswerEvidence.slice(-2).join(" | ") || "None"}
- Retained-tail updates still visible after compaction: ${manifest.retainedTailUpdates.slice(-4).join(" | ") || "None"}
- Latest compacted updates: ${manifest.latestUpdates.slice(-4).join(" | ") || "None"}
- Latest verification and risk signals: ${
		manifest.latestSignals
			.map((signal) => `${signal.kind}: ${signal.text}`)
			.slice(-8)
			.join(" | ") || "None"
	}
- Recent verification: ${manifest.recentVerification.slice(-6).join(" | ") || "None"}
- Open loops/blockers: ${
		manifest.openLoops
			.map((loop) => loop.summary)
			.slice(-6)
			.join(" | ") || "None"
	}
- User decisions/constraints: ${
		[
			...manifest.userDecisions.map((decision) => decision.text),
			...manifest.constraints.map((constraint) => constraint.text),
		]
			.slice(-8)
			.join(" | ") || "None"
	}
- Files read/modified/deleted: ${
		[
			...manifest.filesRead.map((path) => `read ${path}`),
			...manifest.filesModified.map((path) => `modified ${path}`),
			...manifest.filesDeleted.map((path) => `deleted ${path}`),
		]
			.slice(-12)
			.join(" | ") || "None"
	}
- Stale/superseded candidates to treat cautiously: ${
		manifest.staleSignals
			.map((signal) => `${signal.text} (${signal.reason})`)
			.slice(-8)
			.join(" | ") || "None"
	}
- Artifact refs for recovery: ${artifactRefs.slice(-12).join(" | ") || "None"}`;
}

function renderSummaryPrompt(
	snapshot: Snapshot,
	artifactRefs: string[],
	stateEvidence: string,
	conversation: string,
): string {
	const manifest = snapshot.manifest;
	return `You are a Slipstream-style compaction writer for a coding agent.

Write the continuation handoff that a strong next agent would want before taking the next tool call. Optimize for continuation utility, not brevity, keyword recall, or prettiness. The best summary is a dense, source-grounded runbook: current objective, actual latest state, constraints, verification, risks, exact next actions, and enough concrete paths/commands/entities to avoid re-discovery.

Revise the previous checkpoint; do not append stale history. Current/latest user requests, tool results, verification, and state evidence override older summaries when evidence conflicts. State evidence is strong evidence for filesystem/runtime facts, but it does not by itself prove that the user's task is complete or that older in-progress delegation has finished. If transcript state and live state evidence conflict, preserve the conflict and say what to verify next. Do not invent facts, files, commands, tests, decisions, or errors. Preserve uncertainty.

Before writing, run this mental continuation probe:
1. What would the next agent believe is the current task and latest status?
2. What are the next 3 concrete actions it should take?
3. What blockers, failed attempts, unverified claims, and stale/superseded branches could make it go wrong?
4. Which exact files, commands, artifacts, and user decisions are needed to act safely?

Then write a trajectory spine: explain why the next action follows from the latest state, which evidence proves or weakens that state, and what recovery handles let the next agent verify it without rereading the whole transcript. Prefer this causal trajectory over broad historical inventory.

Noise-control rule: foreground only facts that affect the next decision. If the latest state is terminal, post-answer waiting, or a narrow follow-up, keep historical implementation details, dirty working-tree inventories, full artifact paths, and broad critical-file lists terse. Put older details behind recovery handles or stale-context notes instead of repeating them as active work. Do not include compaction-harness, benchmark, scratch-worktree, or unrelated Pi/config git status as current task evidence unless the task itself is about that repo; if such evidence is suspicious, mention only that live repo state must be rechecked before edits. Aim for enough file/command handles to recover, not every possible file ever read. Concision must not erase the latest answer's decision-critical content: preserve the latest assistant response's final verdict, salient risk bullets, verification caveats, and ordered safe-next-step checklist when those facts determine what a future agent should or should not do. Do not replace those facts with only “recover before quoting” unless the retained text is genuinely unavailable.

Start the summary with the exact heading "Continuation card:" in the first screenful, followed by these exact labels when evidence supports them:
- Current task:
- Latest status:
- Next tool action:
- Primary blocker/risk:
- Stale branch to ignore:

Before writing Latest status, Next tool action, and Primary blocker/risk, reconcile the latest user/assistant exchange state, terminal final-answer evidence, retained-tail updates, and Latest verification/risk signals against older summaries, older open loops, and stale candidates. Retained-tail updates are the newest messages still visible after compaction; treat them as current-state anchors, not optional history. Terminal final-answer evidence is protected source text: if it includes a verdict, recommendation, implementation checklist, risk, or verification caveat, carry that content into Latest status, Next Actions, or Blockers/Risks instead of merely listing an artifact/recovery handle. If the latest exchange state says the latest user request already has a subsequent assistant response, do not describe the request as unanswered or the answer as still needing synthesis unless later tool/error evidence after that assistant response proves it was incomplete. If there is no tool activity after the latest assistant response, treat that response as the terminal latest state: demote older pending subagents, in-progress scout/status checks, and “needs synthesis” loops to stale context or recovery handles rather than foregrounding them as Next tool action. New user requests, assistant answers, successful/failing checks, delivered review/final-answer state, dirty-state caveats, and unresolved risks are high-priority current-state evidence. A final_delivered signal is a state lock: if it conflicts with older in-progress loops, pending subagent work, or “needs synthesis” wording, mark those older branches stale unless later evidence reopens the task.

Artifact references are durable local pointers for future tool-assisted recovery, not a substitute for critical current-state facts. Do not make prose summary the only copy of raw code, diffs, JSON/YAML/config, errors, or verification evidence.

Include critical/current protected facts that are needed for safe continuation. You may omit protected facts only when they are stale, superseded, non-continuation-relevant, or safely recoverable from listed artifacts; if omission could mislead the next agent, mention it under stale context or risks. Prefer a slightly longer correct handoff over a clean but under-informative one.

Add a bounded ## Session Findings section for durable facts that are likely useful later in the same session but are not necessarily the immediate next action. Use at most 5 bullets. Include only source-grounded durable facts, investigation conclusions, runbook-level gotchas, artifact locations, or user preferences that would otherwise be easy to lose. Omit transient chatter, raw logs, secrets, broad inventories, and anything already fully captured as current state or stale context.

Required output sections:
## Goal
## Current State
## User Constraints / Preferences
## Completed Work
## Active Decisions
## Trajectory Analysis
## Verification / Evidence
## Session Findings
## Blockers / Risks
## Next Actions
## Critical Files / Artifacts
## Superseded or Stale Context to Ignore

${renderHandoffSignals(snapshot, artifactRefs)}

Protected manifest:

Files read:
${list(manifest.filesRead)}

Files modified:
${list(manifest.filesModified)}

Files deleted:
${list(manifest.filesDeleted)}

Unresolved errors:
${list(manifest.errors.map((e) => e.message))}

User decisions:
${list(manifest.userDecisions.map((d) => d.text))}

Constraints:
${list(manifest.constraints.map((c) => c.text))}

Open loops:
${list(manifest.openLoops.map((l) => l.summary))}

Verification evidence:
${list(manifest.recentVerification)}

Latest compacted updates:
${list(manifest.latestUpdates)}

Retained-tail updates still visible after compaction; these override older compacted updates when they conflict:
${list(manifest.retainedTailUpdates)}

Latest user/assistant exchange state:
${list(manifest.latestExchangeState)}

Terminal final-answer evidence; these exact latest-answer spans override retained-tail truncation:
${list(manifest.terminalFinalAnswerEvidence)}

Latest verification and risk signals:
${list(manifest.latestSignals.map((signal) => `${signal.kind}: ${signal.text}`))}

Stale or superseded candidates:
${list(manifest.staleSignals.map((signal) => `${signal.text} — ${signal.reason}`))}

Critical literals / exact expected strings:
${list(manifest.criticalLiterals)}

Previous checkpoint to revise:
${manifest.previousSummary ?? "None"}

State evidence bundle:
${stateEvidence}

Artifact references:
${list(artifactRefs)}

Conversation span to compact:
<conversation>
${conversation}
</conversation>`;
}

export function buildSummaryPrompt(
	snapshot: Snapshot,
	options: SummaryPromptOptions = {},
): string {
	const artifactRefs = [
		...snapshot.manifest.artifactRefs,
		...(options.artifactRefs ?? []),
	];
	const requestedConversationChars =
		options.maxConversationChars ?? DEFAULT_MAX_CONVERSATION_CHARS;
	const maxPromptChars =
		options.maxPromptChars ?? DEFAULT_MAX_SUMMARY_PROMPT_CHARS;
	const stateEvidence = renderStateEvidence(options.stateEvidence);
	const initialConversation = boundedConversation(
		snapshot.summaryInputMessages,
		requestedConversationChars,
	);
	const initialPrompt = renderSummaryPrompt(
		snapshot,
		artifactRefs,
		stateEvidence,
		initialConversation,
	);
	if (initialPrompt.length <= maxPromptChars) return initialPrompt;

	const skeletonPrompt = renderSummaryPrompt(
		snapshot,
		artifactRefs,
		stateEvidence,
		"",
	);
	if (skeletonPrompt.length >= maxPromptChars) {
		throw new Error(
			`Slipstream summary prompt fixed sections exceed maxPromptChars (${skeletonPrompt.length} >= ${maxPromptChars}); reduce protected manifest/state evidence before retrying.`,
		);
	}
	const remainingConversationChars = Math.max(
		0,
		maxPromptChars - skeletonPrompt.length,
	);
	const cappedConversation = boundedConversation(
		snapshot.summaryInputMessages,
		Math.min(requestedConversationChars, remainingConversationChars),
	);
	const cappedPrompt = renderSummaryPrompt(
		snapshot,
		artifactRefs,
		stateEvidence,
		cappedConversation,
	);
	if (cappedPrompt.length <= maxPromptChars) return cappedPrompt;

	const omittedConversation = boundedConversation(
		snapshot.summaryInputMessages,
		0,
	);
	const omissionOnlyPrompt = renderSummaryPrompt(
		snapshot,
		artifactRefs,
		stateEvidence,
		omittedConversation,
	);
	if (omissionOnlyPrompt.length <= maxPromptChars) return omissionOnlyPrompt;
	throw new Error(
		`Slipstream summary prompt exceeds maxPromptChars after conversation capping (${omissionOnlyPrompt.length} > ${maxPromptChars}); reduce protected manifest/state evidence before retrying.`,
	);
}

export async function generateCandidateSummary(
	snapshot: Snapshot,
	completeText: CompleteTextFn,
	signal?: AbortSignal,
): Promise<string> {
	const summary = await completeText(buildSummaryPrompt(snapshot), signal);
	return summary.trim();
}
